name: simple_note
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter
  google_fonts: ^3.0.1
  logger: ^1.1.0
  flutter_svg: ^1.1.6
  flutter_staggered_grid_view: ^0.6.2
  sqflite: ^2.1.0+1
  path_provider: ^2.0.11
  sharedpreference: ^0.0.1
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
